site_name: ç‹®å­Rraionçš„ç½‘ç«™
site_url: https://RraionWang.github.io
repo_url: https://github.com/RraionWang/RraionWang.github.io

plugins:
  - tags
  # - social  # æš‚æ—¶ç¦ç”¨ social æ’ä»¶ï¼Œé¿å…å› å­—ä½“ä¸‹è½½å¤±è´¥å¯¼è‡´æ„å»ºå¤±è´¥

theme:
  name: 'material'
  palette:
    primary: black
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.path
    - toc.integrate
    - tags
  font:
    text: Roboto Mono  # å¦‚æœ Google Fonts æ— æ³•ä¸‹è½½ï¼Œä½ å¯ä»¥å»æ‰è¿™ä¸€è¡Œæˆ–æ¢æˆæœ¬åœ°å­—ä½“æ–‡ä»¶
    language: zh

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/%E5%B2%A9%E6%9D%BE-%E6%B1%AA-7a469b357/
    - icon: fontawesome/brands/github
      link: https://github.com/RraionWang
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/3546647762045462?spm_id_from=333.1007.0.0
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@rraion4theworld

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  
  - stylesheets/banner.css
  - stylesheets/gantt.css

extra_javascript:
  - scripts/gantt.js
  - scripts/gantt-init.js

nav:

 
  
  - Home: index.md
  

  - äº§å“é‡Œç¨‹ç¢‘: äº§å“é‡Œç¨‹ç¢‘.md
  - äº§å“ç»†èŠ‚: 
        - ğŸ±memeç©å…·: äº§å“ç»†èŠ‚/memeç©å…·.md
        - ğŸ“¸å°ç…§ç›¸æœº: äº§å“ç»†èŠ‚/å°ç…§ç›¸æœº.md

  # - æ ‡ç­¾: tag.md


  - æŠ€æœ¯æ–‡ç« :
      - U8g2:
          - 1. åŸºç¡€çŸ¥è¯†: æŠ€æœ¯æ–‡ç« /U8g2/1_basic/1_basic.md
          - 2. åŸºç¡€æ§ä»¶API: æŠ€æœ¯æ–‡ç« /U8g2/2_graph/2_graph.md
      - mui:
          - 1. åŸºç¡€: æŠ€æœ¯æ–‡ç« /u8g2_mui/1_index/1_index.md
          - 2. è®¾è®¡ä¸€ä¸ªåˆ—è¡¨: æŠ€æœ¯æ–‡ç« /u8g2_mui/2_design_a_list/2_design_a_list.md
          - 3. è®¾è®¡ä¸€ä¸ªä¸Šä¸‹é€‰åˆ—è¡¨: æŠ€æœ¯æ–‡ç« /u8g2_mui/3_design_a_up_and_down_list/3_design_a_up_and_down_list.md

      - ESP-IDF:
          - 1.ç¯å¢ƒæ­å»º: æŠ€æœ¯æ–‡ç« /ESP-IDF/esp_idf_1_config_env/esp_idf_1_config_env.md
          - 2.åŸºç¡€çŸ¥è¯†: æŠ€æœ¯æ–‡ç« /ESP-IDF/esp_idf_2_basic/esp_idf_2_basic.md
          - 3.ç¬¬ä¸€ä¸ªå·¥ç¨‹: æŠ€æœ¯æ–‡ç« /ESP-IDF/esp_idf_3_first_proj/esp_idf_3_first_proj.md
          - 4.åŒæ­¥ï¼Œäº’æ–¥å’Œé˜Ÿåˆ—: æŠ€æœ¯æ–‡ç« /ESP-IDF/esp_idf_4_sync_mutex_queue/esp_idf_4_sync_mutex_queue.md
          - 5.ä¿¡å·: æŠ€æœ¯æ–‡ç« /ESP-IDF/esp_idf_5_semaphore/esp_idf_5_semaphore.md 
          - 6.äº‹ä»¶å’Œå…¶ä»–: æŠ€æœ¯æ–‡ç« /ESP-IDF/esp_idf_6_event_and_other/esp_idf_6_event_and_other.md
          - 7.GPIO: æŠ€æœ¯æ–‡ç« /ESP-IDF/esp_idf_7_gpio/esp_idf_7_gpio.md

      - ç»“æ„è®¾è®¡:
          - XIAOç»“æ„è®¾è®¡: æŠ€æœ¯æ–‡ç« /ç»“æ„è®¾è®¡/xiao/xiao_esp32s3.md
      - æ ‘è“æ´¾:
          - ä½¿ç”¨æ ‘è“æ´¾+OpenWrtå®ç°é­”æ³•è½¯è·¯ç”±: æŠ€æœ¯æ–‡ç« /raspberrypi/pi4_openwrt/pi4_openwrt.md
      - Zdog:
          - ä½¿ç”¨zdogè®¾è®¡ä¸€ä¸ªä¹¦æ¶: æŠ€æœ¯æ–‡ç« /Zdogå­¦ä¹ ç¬”è®°/design_a_shelf.md
      - XIAO:
          - SenseCraftä¸²å£ç»“æ„: æŠ€æœ¯æ–‡ç« /XIAO_ESP32S3åˆé›†/XIAO_ESP323_SenseCraft_format/XIAO_ESP323_SenseCraft_format.md
      - Dockeræœ¬åœ°éƒ¨ç½²å°æ™ºæœåŠ¡å™¨: æŠ€æœ¯æ–‡ç« /Dockeræœ¬åœ°éƒ¨ç½²å°æ™ºæœåŠ¡å™¨/Dockeræœ¬åœ°éƒ¨ç½²å°æ™ºæœåŠ¡å™¨.md
      - Dockeræœ¬åœ°éƒ¨ç½²dify: æŠ€æœ¯æ–‡ç« /Dockeræœ¬åœ°éƒ¨ç½²dify/Dockeræœ¬åœ°éƒ¨ç½²dify.md
      - XIAOæœ€å°Platformioå·¥ç¨‹: æŠ€æœ¯æ–‡ç« /XIAOæœ€å°Platformioå·¥ç¨‹/XIAOæœ€å°Platformioå·¥ç¨‹.md
      - DXFåˆé›†:
          - Seeed Groveä¼ æ„Ÿå™¨:
              - è¶…å£°æ³¢è·ç¦»ä¼ æ„Ÿå™¨: æŠ€æœ¯æ–‡ç« /DXFåˆé›†/XIAO_Grove_Sensor/ultrasonic_distance_sensor.md
      - FreeCAD:
          - ä½¿ç”¨FreeCADè®¾è®¡dxfæ–‡ä»¶: æŠ€æœ¯æ–‡ç« /FreeCAD/ä½¿ç”¨FreeCADè®¾è®¡dxfæ–‡ä»¶/ä½¿ç”¨FreeCADè®¾è®¡dxfæ–‡ä»¶.md




